# Generated by Django 4.0 on 2024-01-25 14:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='John Doe', max_length=25, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.RegexValidator('^.*[a-zA-Z].*[\\w]*$')]),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=69807508, max_length=50, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.RegexValidator('^\\S*$')]),
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(choices=[('secretary', 'secretary'), ('patient', 'patient')], default='patient', max_length=16),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=21219334, max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.RegexValidator('^.*[a-zA-Z].*[\\w]*$')]),
        ),
    ]
