# Generated by Django 4.0 on 2024-01-27 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0002_alter_clinic_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('clinic_name', models.CharField(max_length=200)),
                ('amount_paid', models.FloatField()),
            ],
        ),
    ]
