# Generated by Django 4.0 on 2024-01-27 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0003_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapacityIncrease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('clinic_name', models.CharField(max_length=200)),
                ('increase_amount', models.IntegerField()),
            ],
        ),
    ]
